namespace Choir.FrontEnd.C.Preprocess;

public enum CTokenKind
{
    Invalid,

    Identifier,
    Number,
    LiteralCharacter,
    LiteralString,

    Bang = '!',
    Pound = '#',
    //Dollar = '$',
    Percent = '%',
    Ampersand = '&',
    OpenParen = '(',
    CloseParen = ')',
    Star = '*',
    Plus = '+',
    Comma = ',',
    Minus = '-',
    Dot = '.',
    Slash = '/',
    Colon = ':',
    SemiColon = ';',
    Less = '<',
    Equal = '=',
    Greater = '>',
    Question = '?',
    //At = '@',
    OpenSquare = '[',
    //BackSlash = '\\',
    CloseSquare = ']',
    Caret = '^',
    //Underscore = '_',
    Backtick = '`',
    OpenCurly = '{',
    Pipe = '|',
    CloseCurly = '}',
    Tilde = '~',

    BangEqual,
    PoundPound,
    PercentEqual,
    AmpersandEqual,
    AmpersandAmpersand,
    StarEqual,
    PlusPlus,
    PlusEqual,
    MinusMinus,
    MinusGreater,
    DotDotDot,
    SlashEqual,
    ColonColon,
    LessLess,
    LessLessEqual,
    LessEqual,
    EqualEqual,
    GreaterGreater,
    GreaterGreaterEqual,
    GreaterEqual,
    CaretEqual,
    PipePipe,
    PipeEqual,

    EndOfFile = 255,
}
